name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  nixline-ci:
    uses: Lineage-org/.github/.github/workflows/nixline-ci.yml@stable
    with:
      channel: stable
      consumption_pattern: template
